### ISSUE TITLE
Remove display of result on `viewof`

### ISSUE THREAD

**Issue by nicola** [asg017/dataflow#3]
Cells that have `viewof` are meant to be view and it would be great to remove display of their result (it makes the notebook much cleaner)

**Comment by asg017** [comment]
This is a reasonable request! I will include it in the next dataflow release in the next day or so.

**Comment by asg017** [comment]
This is now the default for dataflow as of `v0.0.4`, the viewof values cells are not displayed. Same with mutable cells as well!

```
md`# #3`

viewof text = html`<input type=text value="yo!">`


md`Text: **${text}**`
```

![image](https://user-images.githubusercontent.com/15178711/115271877-a672c000-a0f2-11eb-94b3-dc2786b3966b.png)
