### ISSUE TITLE
403 Forbidden when trying to load FileAttachment

### ISSUE THREAD

**Issue by GabiSchaffzin** [asg017/dataflow#36]
Apologies if this is out of scope of dataflow. My ojs file reads one line:

`data = FileAttachment("census.json").json()`

My file structure is as such:

```
dataflow
│   example.ojs
│   census.json
```

The contents of the json file are from the census example, [here](https://cdn.jsdelivr.net/npm/us-atlas@3/counties-albers-10m.json).

But when I run, I receive the error on the page:

`data = Error: Unable to load file: census.json`

And in the console:

`[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (file-attachments, line 0)     http://localhost:8080/api/file-attachments?name=census.json`

There are no errors in the console, just `[2024-11-27T20:04:57.267Z] GET /api/file-attachments?name=census.json`

I'm using Safari 17.6 on macOS 14.6.1

**Comment by asg017** [comment]
Run with the `--allow-file-attachments` flag: https://alexgarcia.xyz/dataflow/docs/#file-attachments

Otherwise this project is pretty old and isn't maintained, take a look at [Observable Framework](https://observablehq.com/framework/) for a much better selfhost'able  notebook solution

**Comment by GabiSchaffzin** [comment]
Understood—thank you!
